# Site settings
title: Desiree Hinshaw
email: DesireeHinshaw@gmail.com
url: https://DesireeHinshaw.github.io
description: "Desiree Hinshaw's Website for Game Design."
keywords: "e-sports, pilot, games, gaming, game design, resume, wichita, kansas, ks"
skills: "Game Designer - Pilot - Best Sister"
meta_author: Hinshaw Desiree

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Desi

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 76ba85 #18bc9c #80B3FF
  primary-rgb: "128,179,255" #"24,288,156" 
  secondary: 363d5f  #FD6E8A
  secondary-dark: c44c60 #A2122F

# Footer settings
footer:
  copyright: Desiree Hinshaw
  location: Location
  social: Social Media
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/DesireeHinshaw

  - title: facebook
    url: https://www.facebook.com/desiree.hinshaw

  - title: instagram
    url: https://www.instagram.com/desi_mae/

  - title: linkedin
    url: https://www.linkedin.com/onboarding/start/people-you-may-know/existing/

  - title: itch-io
    url: https://desimae.itch.io/

# Postal address (add as many lines as necessary)
address:
  - line: Wichita,
  - line: Kansas

# Credits content
credits: 'Built with HTML, CSS. Generated with Jekyll on Github.'

# Build settings
markdown: kramdown
permalink: pretty
